#!/bin/ksh --login
echo 'into'
source /u/Alicia.Bentley/.bashrc
cyc=$1

mkdir -p /gpfs/dell1/stmp/Alicia.Bentley
mkdir -p /gpfs/dell1/stmp/Alicia.Bentley/gefs
cd /gpfs/dell1/stmp/Alicia.Bentley/gefs


year=`cut -c 1-4 holddate.txt`
month=`cut -c 5-6 holddate.txt`
day=`cut -c 7-8 holddate.txt`
hour=`cut -c 9-10 holddate.txt`
dow=`cut -c 11-13 holddate.txt`
ymdh=${year}${month}${day}${hour}
ymdhdow=${year}${month}${day}${hour}${dow}


python /gpfs/dell2/emc/verification/save/Alicia.Bentley/gefs/makegefs2mrhcsv.py $ymdh &
python /gpfs/dell2/emc/verification/save/Alicia.Bentley/gefs/makegefsshearcsv.py $ymdh &
wait

exit


